---
#extract the zipped artifact into the EC2 instance, 
- name: make new directory
  file:
    path: /home/ubuntu/app
    state: directory
  become: true
  become_method: sudo

- name: extract the zipped artifact into the EC2 instance
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/app
  become: true
  become_method: sudo

#and then start the app., npm install, pm2 stop default, pm2 start npm -- start
- name: install npm
  shell: npm install
  args:
    chdir: /home/ubuntu/app
  become: true
  become_method: sudo

#- name: stop the app
#  shell: pm2 stop default
#  become: true
#  become_method: sudo

- name: start the app
  shell: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/app
  become: true
  become_method: sudo
