---


- name: install dependencies
  become: true
  apt:
    name: 
     - npm
     - nodejs
    state: latest
    update_cache: yes
  
- name: artifact to instance 
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start app
  become: true
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start
